# Generated by Django 3.1.6 on 2021-09-12 06:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0003_auto_20210912_1054'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contest',
            name='enable_leaderboard',
        ),
        migrations.RemoveField(
            model_name='contest',
            name='show_leaderboard',
        ),
    ]
